# Generated by Django 4.1.4 on 2023-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(blank=True)),
                ('wind_kph', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('wind_dir', models.CharField(blank=True, max_length=3)),
                ('humidity', models.IntegerField(blank=True)),
                ('gusts_kph', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('air_quality_index', models.IntegerField(blank=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('precipation', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('cloud', models.IntegerField(blank=True)),
            ],
        ),
    ]
