# Generated by Django 4.1.4 on 2023-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
