# Generated by Django 4.1.4 on 2023-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weather_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='last_updated',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
